repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.8.6
  hooks:
    # Run the linter.
    # TODO fix the lint issues for the Jupyter notebooks
    - id: ruff
      types_or: [ python, pyi ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]
